- name: Create calculator container using calc image
  hosts: client1
  become: yes
  tasks:
    - name: pull the docker image from hub 'murphy961/spe_devops'
      shell:
        docker pull murphy961/spe_devops:1.0
    - name: create container using pulled image
      shell:
        docker stop calc&&docker rm calc&&docker run -itd --name calc murphy961/spe_devops:1.0
#        &&gnome-terminal -- bash -c "docker attach calc; exec bash"